python /projects/shart/digital_pathology/scripts/General-ImageClassifier/train.py  -t /projects/shart/digital_pathology/data/BACH/final_train_test_val/train -v /projects/shart/digital_pathology/data/BACH/final_train_test_val/val  -m DenseNet201  -o Adam  -p 256  -l /projects/shart/digital_pathology/data/BACH/LOG_last_Layer_DO_0.25  -r 0.00001  -L BinaryCrossentropy  -e 50 -b 64  -V DEBUG  --use-multiprocessing True --filetype images -D 0.25
python /projects/shart/digital_pathology/scripts/General-ImageClassifier/train.py  -t /projects/shart/digital_pathology/data/BACH/final_train_test_val/train -v /projects/shart/digital_pathology/data/BACH/final_train_test_val/val  -m DenseNet201  -o Adam  -p 256  -l /projects/shart/digital_pathology/data/BACH/LOG_last_Layer_DO_0.5  -r 0.00001  -L BinaryCrossentropy  -e 50 -b 64  -V DEBUG  --use-multiprocessing True --filetype images -D 0.5
python /projects/shart/digital_pathology/scripts/General-ImageClassifier/train.py  -t /projects/shart/digital_pathology/data/BACH/final_train_test_val/train -v /projects/shart/digital_pathology/data/BACH/final_train_test_val/val  -m DenseNet201  -o Adam  -p 256  -l /projects/shart/digital_pathology/data/BACH/LOG_last_Layer_DO_0.75  -r 0.00001  -L BinaryCrossentropy  -e 50 -b 64  -V DEBUG  --use-multiprocessing True --filetype images -D 0.75
python /projects/shart/digital_pathology/scripts/General-ImageClassifier/train.py  -t /projects/shart/digital_pathology/data/BACH/final_train_test_val/train -v /projects/shart/digital_pathology/data/BACH/final_train_test_val/val  -m DenseNet201  -o Adam  -p 256  -l /projects/shart/digital_pathology/data/BACH/LOG_last_Layer/  -r 0.001  -L BinaryCrossentropy  -e 50 -b 64  -V DEBUG  --use-multiprocessing True --filetype images 
python /projects/shart/digital_pathology/scripts/General-ImageClassifier/train.py  -t /projects/shart/digital_pathology/data/BACH/final_train_test_val/train -v /projects/shart/digital_pathology/data/BACH/final_train_test_val/val  -m DenseNet201  -o Adam  -p 256  -l /projects/shart/digital_pathology/data/BACH/LOG_last_Layer/  -r 0.005  -L BinaryCrossentropy  -e 50 -b 64  -V DEBUG  --use-multiprocessing True --filetype images 
python /projects/shart/digital_pathology/scripts/General-ImageClassifier/train.py  -t /projects/shart/digital_pathology/data/BACH/final_train_test_val/train -v /projects/shart/digital_pathology/data/BACH/final_train_test_val/val  -m DenseNet201  -o Adam  -p 256  -l /projects/shart/digital_pathology/data/BACH/LOG_last_Layer/  -r 0.0001  -L BinaryCrossentropy  -e 50 -b 64  -V DEBUG  --use-multiprocessing True --filetype images 
python /projects/shart/digital_pathology/scripts/General-ImageClassifier/train.py  -t /projects/shart/digital_pathology/data/BACH/final_train_test_val/train -v /projects/shart/digital_pathology/data/BACH/final_train_test_val/val  -m DenseNet201  -o Adam  -p 256  -l /projects/shart/digital_pathology/data/BACH/LOG_last_Layer/  -r 0.0005  -L BinaryCrossentropy  -e 50 -b 64  -V DEBUG  --use-multiprocessing True --filetype images 
python /projects/shart/digital_pathology/scripts/General-ImageClassifier/train.py  -t /projects/shart/digital_pathology/data/BACH/final_train_test_val/train -v /projects/shart/digital_pathology/data/BACH/final_train_test_val/val  -m DenseNet201  -o Adam  -p 256  -l /projects/shart/digital_pathology/data/BACH/LOG_last_Layer/  -r 0.000001  -L BinaryCrossentropy  -e 50 -b 64  -V DEBUG  --use-multiprocessing True --filetype images 
python /projects/shart/digital_pathology/scripts/General-ImageClassifier/train.py  -t /projects/shart/digital_pathology/data/BACH/final_train_test_val/train -v /projects/shart/digital_pathology/data/BACH/final_train_test_val/val  -m DenseNet201  -o Adam  -p 256  -l /projects/shart/digital_pathology/data/BACH/LOG_all_Layers/  -r 0.00001  -L BinaryCrossentropy  -e 50 -b 64  -V DEBUG  --use-multiprocessing True --filetype images --train_num_layers 0 --prev_checkpoint /projects/shart/digital_pathology/data/BACH/LOG_last_Layer/DenseNet201_Adam_1e-05-BinaryCrossentropy/cp-0007.ckpt 
python /projects/shart/digital_pathology/scripts/General-ImageClassifier/train.py  -t /projects/shart/digital_pathology/data/BACH/final_train_test_val/train -v /projects/shart/digital_pathology/data/BACH/final_train_test_val/val  -m DenseNet201  -o Adam  -p 256  -l /projects/shart/digital_pathology/data/BACH/LOG_last_Layer_DO_0.5_L2_0.01  -r 0.00001  -L BinaryCrossentropy  -e 150 -b 64  -V DEBUG  --use-multiprocessing True --filetype images -D 0.5 -R 0.01
